task:
  name: cirrus-tests
  container:
    image: python:latest
  source_env_script:
    - pwd
    - ls 
    - ls $CIRRUS_WORKING_DIR/*
    - cat $CIRRUS_WORKING_DIR/.env
    - source $CIRRUS_WORKING_DIR/.env
    - apt update
    - apt install rclone
  show_script:
    - cat requirements.txt
    - pip install -r requirements.txt
    - rclone --version
    - echo $BIN
    - echo $HOME
    - ls $HOME
    - python -c "from pathlib import Path;print(print(Path.home()))"

